package Juego;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.plaf.basic.BasicComboBoxRenderer;

public class Nivel extends javax.swing.JPanel implements KeyListener{

    public static JLabel cuphead = new JLabel();
    public static JLabel jefe = new JLabel();
    public static JLabel escenario = new JLabel();
    public static JLabel disparo1 = new JLabel();
    public static JLabel disparo2 = new JLabel();
    public static JLabel disparojefe = new JLabel();
    public static JLabel[] vectorDisparo =  new JLabel[1000];
    public static int x1 = 0;
    public static int x2 = 1150;
    
    public Nivel() {
        initComponents();
        cuphead.setBounds(100, 550, 300, 300);
        jefe.setBounds(1100, 550, 300, 300);
        disparojefe.setBounds(1000, 550, 200, 200);
        escenario.setSize(1400,850);
        disparo1.setBounds(200, 550, 150, 150);
        disparo2.setBounds(200, 550, 250, 250);
        disparo1.setVisible(false);
        disparo2.setVisible(false);
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Resources/Jefe.gif"));
        Icon logo = new ImageIcon(imagen.getImage().getScaledInstance(jefe.getWidth(),jefe.getHeight(), Image.SCALE_DEFAULT));
        jefe.setIcon(logo);
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Resources/Cuphead.png"));
        Icon logo2 = new ImageIcon(imagen2.getImage().getScaledInstance(cuphead.getWidth(),cuphead.getHeight(), Image.SCALE_DEFAULT));
        cuphead.setIcon(logo2);
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Resources/Escenario.jpg"));
        Icon logo3 = new ImageIcon(imagen3.getImage().getScaledInstance(escenario.getWidth(),escenario.getHeight(), Image.SCALE_DEFAULT));
        escenario.setIcon(logo3);
        ImageIcon imagen4 = new ImageIcon(getClass().getResource("/Resources/disparo1.png"));
        Icon logo4 = new ImageIcon(imagen4.getImage().getScaledInstance(disparo1.getWidth(),disparo1.getHeight(), Image.SCALE_DEFAULT));
        disparo1.setIcon(logo4);
        ImageIcon imagen5 = new ImageIcon(getClass().getResource("/Resources/disparo2.png"));
        Icon logo5 = new ImageIcon(imagen5.getImage().getScaledInstance(disparo2.getWidth(),disparo2.getHeight(), Image.SCALE_DEFAULT));
        disparo2.setIcon(logo5);
        ImageIcon imagen6 = new ImageIcon(getClass().getResource("/Resources/disparojefe.png"));
        Icon logo6 = new ImageIcon(imagen6.getImage().getScaledInstance(disparojefe.getWidth(),disparojefe.getHeight(), Image.SCALE_DEFAULT));
        disparojefe.setIcon(logo6);
        addKeyListener(this);
        setFocusable(true);
        for(int i=0; i<vectorDisparo.length;i++){
            vectorDisparo[1]=disparo1;
        }
        add(jefe);
        add(disparo1);
        add(disparo2);
        add(cuphead);
        add(escenario);
        add(disparojefe);
        HiloJefe hilo = new HiloJefe();
        hilo.start();
        HiloDisparoJefe dispjefe = new HiloDisparoJefe();
        dispjefe.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void keyPressed(KeyEvent e) {
   if(e.getKeyChar()== Config.atras.charAt(0) ||e.getExtendedKeyCode()==KeyEvent.VK_LEFT){
           if(cuphead.getX()>-x1){
         cuphead.setLocation(cuphead.getX()-35,cuphead.getY());
         }else{
         cuphead.setLocation(cuphead.getX(),cuphead.getY()); 
         } 
     }
   if(e.getKeyChar()== Config.adelante.charAt(0)){
         if(cuphead.getX()<x2){
         cuphead.setLocation(cuphead.getX()+35,cuphead.getY());
         }else{
         cuphead.setLocation(cuphead.getX(),cuphead.getY()); 
         } 
   }
      if(e.getKeyChar()== Config.salto.charAt(0)){
         cuphead.setLocation(cuphead.getX(),cuphead.getY()-200);
       }
      if(e.getKeyChar()== Config.disp1.charAt(0)){
          HiloDisparo1 disp1 = new HiloDisparo1();
          disp1.start();
      }
        if (e.getKeyChar()== Config.disp2.charAt(0)) {
            HiloDisparo2 disp2 = new HiloDisparo2();
            disp2.start();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
   
      if(e.getKeyChar()== Config.salto.charAt(0)){
         cuphead.setLocation(cuphead.getX(),550);
       }
    }

    @Override
    public void keyTyped(KeyEvent ke) {
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
