/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;
import Logica.Listas;
import Logica.Curso;
import javax.swing.JOptionPane;
/**
 *
 * @author Elder
 */
public class agregarCurso extends javax.swing.JFrame {
private String nocurso, nombreCurso, catedratico, lab, seccion, prerequisito, postrequisito;
private int creditos;
    /**
     * Creates new form agregarCurso
     */
    public agregarCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtcurso = new javax.swing.JTextField();
        txtnombrecurso = new javax.swing.JTextField();
        txtcatedratico = new javax.swing.JTextField();
        txtcredito = new javax.swing.JTextField();
        txtseccion = new javax.swing.JTextField();
        txtpre = new javax.swing.JTextField();
        btnagregar2 = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        combolab = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txtpost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGREGAR CURSO");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel17.setText("Agregar Curso");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel18.setText("No. de Curso:");

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel19.setText("Nombre:");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel20.setText("Catedrático:");

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel21.setText("Créditos:");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel22.setText("Laboratorio:");

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel23.setText("Sección:");

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel24.setText("Pre-Requisito:");

        txtcurso.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        txtcurso.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtnombrecurso.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        txtnombrecurso.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtcatedratico.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        txtcatedratico.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtcredito.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        txtcredito.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtseccion.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        txtseccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtpre.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        txtpre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnagregar2.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btnagregar2.setText("Agregar");
        btnagregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar2ActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        combolab.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        combolab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "N" }));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel25.setText("Post-Requisito:");

        txtpost.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        txtpost.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(76, 76, 76))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcurso)
                            .addComponent(txtnombrecurso)
                            .addComponent(txtcatedratico)
                            .addComponent(txtcredito)
                            .addComponent(txtseccion)
                            .addComponent(txtpre)
                            .addComponent(combolab, 0, 146, Short.MAX_VALUE)
                            .addComponent(txtpost)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnagregar2)
                        .addGap(35, 35, 35)
                        .addComponent(btncancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtnombrecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtcatedratico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtcredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(combolab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtseccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar2)
                    .addComponent(btncancelar)
                    .addComponent(btnsalir))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar2ActionPerformed
        nocurso = txtcurso.getText();
        nombreCurso = txtnombrecurso.getText();
        catedratico = txtcatedratico.getText();
        lab = (String) combolab.getSelectedItem();
        creditos = Integer.parseInt(txtcredito.getText());
        seccion = txtseccion.getText();
        prerequisito = txtpre.getText();
        postrequisito = txtpost.getText();
        Curso curso = new Curso(nocurso, nombreCurso, catedratico, creditos, lab, seccion, prerequisito.split(","), postrequisito);
        int x = JOptionPane.showConfirmDialog(null, "¿Desea agregar este nuevo Curso?", "Sistema SECY", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Curso agregado con éxito.", "Sistema SECY", JOptionPane.INFORMATION_MESSAGE);
            Listas.curso.agregarInicio(curso);
            txtcurso.setText("");
            txtnombrecurso.setText("");
            txtcatedratico.setText("");
            txtcredito.setText("");
            txtseccion.setText("");
            txtpre.setText("");
            txtpost.setText("");
            Listas.curso.getLongitud();
        }else{
            JOptionPane.showMessageDialog(null, "Operación Cancelada.", "Sistema SECY", JOptionPane.INFORMATION_MESSAGE);
        }

        Curso puntero = Listas.curso.getInicio();
        for(int i = 0; i<Listas.curso.getLongitud(); i++) {
            System.out.println("Id: " + puntero.getNocurso()+ "  /  Nombre: " + puntero.getNombreCurso() + "  /  Lab: " + puntero.getLab());
            puntero = puntero.getSiguiente();
        }
    }//GEN-LAST:event_btnagregar2ActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        txtcurso.setText("");
        txtnombrecurso.setText("");
        txtcatedratico.setText("");
        txtcredito.setText("");
        txtseccion.setText("");
        txtpre.setText("");
        txtpost.setText("");
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        CrudCurso curso = new CrudCurso();
        curso.setVisible(true);
        curso.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar2;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> combolab;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtcatedratico;
    private javax.swing.JTextField txtcredito;
    private javax.swing.JTextField txtcurso;
    private javax.swing.JTextField txtnombrecurso;
    private javax.swing.JTextField txtpost;
    private javax.swing.JTextField txtpre;
    private javax.swing.JTextField txtseccion;
    // End of variables declaration//GEN-END:variables
}
