/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;
import Logica.Listas;
import javax.swing.JOptionPane;
/**
 *
 * @author Elder
 */
public class modCurso extends javax.swing.JFrame {

    /**
     * Creates new form modCurso
     */
    public modCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnocurso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcatedratico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcreditos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtlab = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtseccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtpost = new javax.swing.JTextField();
        btnmodificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MODIFICAR CURSO");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel2.setText("No. de Curso:");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel3.setText("Nombre Curso:");

        txtnombre.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel4.setText("Catedrático:");

        txtcatedratico.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel5.setText("Créditos:");

        txtcreditos.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel6.setText("Laboratorio:");

        txtlab.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel7.setText("Sección:");

        txtseccion.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel8.setText("Pre-Requisito:");

        txtpre.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel9.setText("Post-Requisito:");

        txtpost.setEnabled(false);

        btnmodificar.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setEnabled(false);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setText("Eliminar Curso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtpost)
                            .addComponent(txtpre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtseccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlab, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcreditos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnocurso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcatedratico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btncancelar)
                                .addGap(48, 48, 48)
                                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnmodificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnocurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcatedratico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtlab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtseccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodificar)
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar)
                    .addComponent(btnsalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        String[] y = new String[1];
        for (int i = 0; i < y.length; i++) {
        y[i] = txtpre.getText();
        int x = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este Curso?", "Sistema SECY", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            try{
                Listas.curso.editar(txtnocurso.getText(), txtnombre.getText(), txtcatedratico.getText(), Integer.parseInt(txtcreditos.getText()), txtlab.getText(), txtseccion.getText(), y[i].split(","), txtpost.getText());
                btncancelar.setEnabled(false);
                btnmodificar.setEnabled(false);
                btnbuscar.setEnabled(true);
                txtnocurso.setText("");
                txtnombre.setText("");
                txtcatedratico.setText("");
                txtcreditos.setText("");
                txtlab.setText("");
                txtseccion.setText("");
                txtpre.setText("");
                txtpost.setText("");
            }catch (Exception e){
                System.out.println("Esto no sirve >:c");
                btncancelar.setEnabled(true);
                btnmodificar.setEnabled(true);
                btnbuscar.setEnabled(false);
            }
            JOptionPane.showConfirmDialog(null, "Curso Modificado con éxito.", "Sistema SECY", JOptionPane.OK_OPTION);
        }else{
            JOptionPane.showMessageDialog(null, "Operación Cancelada.", "Sistema SECY", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        txtnocurso.setText("");
        txtnombre.setText("");
        txtcatedratico.setText("");
        txtcreditos.setText("");
        txtlab.setText("");
        txtseccion.setText("");
        txtpre.setText("");
        txtpost.setText("");
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        CrudCurso curso = new CrudCurso();
        curso.setVisible(true);
        curso.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String carnet = txtnocurso.getText();
        String[] y = new String[1];
        for (int i = 0; i < y.length; i++) {
        try{
            txtnombre.setEnabled(true);
            txtcatedratico.setEnabled(true);
            txtcreditos.setEnabled(true);
            txtlab.setEnabled(true);
            txtseccion.setEnabled(true);
            txtpre.setEnabled(true);
            txtpost.setEnabled(true);
            txtnombre.setText(Listas.curso.buscarNodo(carnet).getNombreCurso());
            txtcatedratico.setText(Listas.curso.buscarNodo(carnet).getCatedratico());
            txtcreditos.setText(String.valueOf(Listas.curso.buscarNodo(carnet).getCreditos()));
            txtlab.setText(Listas.curso.buscarNodo(carnet).getLab());
            txtseccion.setText(Listas.curso.buscarNodo(carnet).getSeccion());
            txtpre.setText(Listas.curso.buscarNodo(carnet).getPrerequisito().toString().split(",").toString());
            txtpost.setText(Listas.curso.buscarNodo(carnet).getPostrequisito());
            btnmodificar.setEnabled(true);
            btncancelar.setEnabled(true);
            btnbuscar.setEnabled(false);
        }catch (Exception e){
            System.out.println("Esto no funciona >:c");
            JOptionPane.showMessageDialog(null, "Curso No Encontrado", "Sistema SECY", JOptionPane.ERROR_MESSAGE);
            txtnombre.setEnabled(false);
            txtcatedratico.setEnabled(false);
            txtcreditos.setEnabled(false);
            txtlab.setEnabled(false);
            txtseccion.setEnabled(false);
            txtpre.setEnabled(false);
            txtpost.setEnabled(false);
            btncancelar.setEnabled(false);
            btnmodificar.setEnabled(false);
            btnbuscar.setEnabled(true);
        }
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcatedratico;
    private javax.swing.JTextField txtcreditos;
    private javax.swing.JTextField txtlab;
    private javax.swing.JTextField txtnocurso;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpost;
    private javax.swing.JTextField txtpre;
    private javax.swing.JTextField txtseccion;
    // End of variables declaration//GEN-END:variables
}
