/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Logica.ManejadorAsignaciones;
import Logica.Semestre;
import Logica.Estudiante;
import Logica.PasswordGenerator;
import Logica.Listas;
import Logica.Curso;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Elder
 */
public class ventanaAdmin extends javax.swing.JFrame {
    
    public static int anio = 2018;
    public static int numsemestre = 1;
    public static boolean bandera = false;
    private ManejadorAsignaciones asignacion = new ManejadorAsignaciones();
    public ventanaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnestudiante = new javax.swing.JButton();
        btncurso = new javax.swing.JButton();
        btncatedratico = new javax.swing.JButton();
        btnreporte = new javax.swing.JButton();
        btnsimular = new javax.swing.JButton();
        btncarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VENTANA DEL ADMINISTRADOR");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnlogout.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel4.setText("Ventana del Administrador");

        btnestudiante.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btnestudiante.setText("Administrar Estudiantes");
        btnestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnestudianteActionPerformed(evt);
            }
        });

        btncurso.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btncurso.setText("Administrar Cursos");
        btncurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncursoActionPerformed(evt);
            }
        });

        btncatedratico.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btncatedratico.setText("Administrar Catedráticos");
        btncatedratico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatedraticoActionPerformed(evt);
            }
        });

        btnreporte.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btnreporte.setText("Reportes del Admin");

        btnsimular.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btnsimular.setText("Simulación de Semestre");
        btnsimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimularActionPerformed(evt);
            }
        });

        btncarga.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        btncarga.setText("Carga Masiva de Datos");
        btncarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnreporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncurso, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsimular, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncarga, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncatedratico))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnlogout))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnestudiante)
                    .addComponent(btncatedratico)
                    .addComponent(btncurso))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreporte)
                    .addComponent(btnsimular)
                    .addComponent(btncarga))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "¿Está Seguro en Cerrar la Sesión?", "Sistema SECY", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Cerrando Sesión, no apague el equipo...", "Sistema SECY", JOptionPane.INFORMATION_MESSAGE);
            ventanaInicial inicial = new ventanaInicial();
            inicial.setVisible(true);
            inicial.setLocationRelativeTo(null);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Operación Cancelada", "Sistema SECY", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnestudianteActionPerformed
        CrudEstudiante estudiante = new CrudEstudiante();
        estudiante.setVisible(true);
        estudiante.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnestudianteActionPerformed

    private void btncursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncursoActionPerformed
        CrudCurso curso = new CrudCurso();
        curso.setVisible(true);
        curso.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btncursoActionPerformed

    private void btncatedraticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatedraticoActionPerformed
        CrudCatedratico cat = new CrudCatedratico();
        cat.setVisible(true);
        cat.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btncatedraticoActionPerformed

    private void btncargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargaActionPerformed
        String[] options = {"Estudiantes", "Catedráticos", "Cursos"};
        int x = JOptionPane.showOptionDialog(null, "Por favor, escoja que tipo de archivo quiere cargar.",
                "Sistema SECY",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        if (x == 0) {
            JFileChooser selectorArchivos = new JFileChooser();
            selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            int resultado = selectorArchivos.showOpenDialog(this); 
            File f = selectorArchivos.getSelectedFile();
            BufferedReader br=null;
        try {
            if(f.exists()){
                br=new BufferedReader(new FileReader(f));
                String linea=br.readLine();
                while(linea!=null){
                    String Datos[]=linea.split(";");
                    String a = PasswordGenerator.getPassword(PasswordGenerator.MAYUSCULAS,1);
                    String b = PasswordGenerator.getPassword(PasswordGenerator.NUMEROS,1);
                    String c = PasswordGenerator.getPassword(PasswordGenerator.MINUSCULAS,1);
                    String d = PasswordGenerator.getPassword(PasswordGenerator.NUMEROS,1);
                    //se ingresan datos al metodo
                    //los datos estasn separados como vector donde la posicion 0 es el primer valor
                    System.out.println("Carnet: "+Datos[0]);
                    System.out.println("DPI: "+Datos[1]);
                    System.out.println("Nombre: "+Datos[2]);
                    System.out.println("Correo: "+Datos[3]);
                    System.out.println("Dirección: "+Datos[4]);
                    System.out.println("No. Créditos: "+Datos[5]);
                    Estudiante estudiante = new Estudiante(Datos[0],Datos[1],Datos[2],Datos[3],Datos[4],Integer.parseInt(Datos[5]),Datos[0]+a+b+c+d);
                    Listas.estudiante.agregarInicio(estudiante);
                    //esto siempre va
                    linea=br.readLine();
                }
                br.close();
            }else{
                System.err.println("Error en la carga del archivo");
            }
        } catch (Exception e) {
            System.err.println("Error al abrir el Archivo");
        }
        }else if (x == 1) {
            JFileChooser selectorArchivos = new JFileChooser();
            selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            int resultado = selectorArchivos.showOpenDialog(this); 
            File f = selectorArchivos.getSelectedFile();
            BufferedReader br=null;
        try {
            if(f.exists()){
                br=new BufferedReader(new FileReader(f));
                String linea=br.readLine();
                while(linea!=null){
                    String Datos[]=linea.split(";");
                    String a = PasswordGenerator.getPassword(PasswordGenerator.MAYUSCULAS,1);
                    String b = PasswordGenerator.getPassword(PasswordGenerator.NUMEROS,1);
                    String c = PasswordGenerator.getPassword(PasswordGenerator.MINUSCULAS,1);
                    String d = PasswordGenerator.getPassword(PasswordGenerator.NUMEROS,1);
                    //se ingresan datos al metodo
                    //los datos estasn separados como vector donde la posicion 0 es el primer valor
                    System.out.println("Registro: "+Datos[0]);
                    System.out.println("Nombre: "+Datos[1]);
                    System.out.println("Dirección: "+Datos[2]);
                    System.out.println("Correo:: "+Datos[3]);
                    Listas.catedratico.apilar(Datos[0],Datos[1],Datos[2],Datos[3],Datos[0]+a+b+c+d);
                    //esto siempre va
                    linea=br.readLine();
                }
                br.close();
            }else{
                System.err.println("Error en la carga del archivo");
            }
        } catch (Exception e) {
            System.err.println("Error al abrir el Archivo");
        }
        
        }else if (x == 2) {
            JFileChooser selectorArchivos = new JFileChooser();
            selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            int resultado = selectorArchivos.showOpenDialog(this); 
            File f = selectorArchivos.getSelectedFile();
            BufferedReader br=null;
        try {
            if(f.exists()){
                br=new BufferedReader(new FileReader(f));
                String linea=br.readLine();
                while(linea!=null){
                    String Datos[]=linea.split(";");
                    //se ingresan datosal metodo
                    //los datos estasn separados como vector donde la posicion 0 es el primer valor
                    System.out.println("No. Curso:"+Datos[0]);
                    System.out.println("Curso :"+Datos[1]);
                    System.out.println("Catedrático :"+Datos[2]);
                    System.out.println("Créditos: "+Datos[3]);
                    System.out.println("Laboratorio: "+Datos[4]);
                    System.out.println("Sección: "+Datos[5]);
                    System.out.println(Datos.length);
                    //en la posicion 6 se almacenan los prerequisitos
                    //esto es si tiene prerequisito
                    if (8==Datos.length){
                        System.out.println("Prerequisitos:"+Datos[6]);
                    //empezamos a separar por filas
                    String Pre[]=Datos[6].split(",");
                    //esto es un ejemplo de como podes administrar los prerequisitos
                    System.out.println("Prerequisito1 :"+Pre[0]);
                    //tome el tamanio por si tiene varios o solo uno
                    if(Pre.length==2){
                        System.out.println("Prerequisito2 :"+Pre[1]);
                    }
                    if(Pre.length==3){
                        System.out.println("Prerequisito2 :"+Pre[1]);
                        System.out.println("Prerequisito3 :"+Pre[2]);
                    }
                    String[]enviar = new String[Pre.length];
                        for (int i = 0; i < Pre.length; i++) {
                            enviar[i] = Pre[i].toString();
                        }
                        
                    Curso cursos = new Curso(Datos[0],Datos[1],Datos[2],Integer.parseInt(Datos[3]),Datos[4],Datos[5], enviar,Datos[7]);
                    Listas.curso.agregarInicio(cursos);
                    }else{
                        //no tiene prerequisito
                        //
                        System.out.println("No tiene prerequisito");
                    }
                    linea=br.readLine();
                }
                br.close();
            }else{
                System.err.println("Error en la carga del archivo");
            }
        } catch (Exception e) {
            System.err.println("Error al abrir el Archivo");
        }
        }else{
            System.err.println("Esta mamada no sirve :c");
        }
    }//GEN-LAST:event_btncargaActionPerformed

    private void btnsimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimularActionPerformed
        Semestre sem = new Semestre(anio, numsemestre, bandera);
        if (numsemestre == 1) {
            numsemestre = numsemestre +1;
            System.out.println(numsemestre);
            System.out.println(anio);
            System.out.println(bandera);
            Listas.semestre.agregarInicio(sem);
            JOptionPane.showMessageDialog(null, "Simulación de Semestre Completada", "Sistema SECY", JOptionPane.INFORMATION_MESSAGE);
        }else if (numsemestre == 2) {
            anio = anio + 1;
            numsemestre = numsemestre - 1;
            System.out.println(numsemestre);
            System.out.println(anio);
            System.out.println(bandera);
            Listas.semestre.agregarInicio(sem);
            JOptionPane.showMessageDialog(null, "Simulación de Semestre Completada", "Sistema SECY", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnsimularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncarga;
    private javax.swing.JButton btncatedratico;
    private javax.swing.JButton btncurso;
    private javax.swing.JButton btnestudiante;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreporte;
    private javax.swing.JButton btnsimular;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
